version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data:
